# Generated by Django 5.2.4 on 2025-07-31 14:00

import content_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(blank=True, choices=[('MOVIE', 'Movie'), ('TUTORIAL', 'Tutorial'), ('VLOG', 'Vlog'), ('MUSIC', 'Music Video'), ('NEWS', 'News'), ('GAMING', 'Gaming'), ('DOCUMENTARY', 'Documentary')], default='MOVIE', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=content_app.models.upload_video_path, validators=[content_app.models.validate_video_file_extension])),
            ],
        ),
    ]
